include:
  template: Dependency-Scanning.gitlab-ci.yml

image: gcc

allyesconfig:
  allow_failure: true
  stage: build
  before_script:
    - make allyesconfig
  script:
    - make

flawfinder:
  stage: test
  before_script:
    - apt update
    - apt install -y flawfinder
  script:
    - flawfinder .
